### ISSUE TITLE
Auto-detection of touchpad is not good enough, e.g. on macOS

### ISSUE THREAD

**Issue by kristianserrano** [shemetz/ZoomPanOptions#30]
On macOS, it seems the module detects a trackpad regardless of whether or not a trackpad is actually connected. Additionally, if a user is using a mouse, the default assumption of the use of a trackpad disrupts that default use of the scroll wheel to zoom.

Food for thought: I question the reliability of auto-detecting to determine a default behavior. I think it should default to core, and a user should select which variant they'd prefer.

**Comment by itamarcu** [comment]
Alright, for now you can use the "Default Mouse" setting to get around this issue (or "Touchpad" when using touchpad).  I'm not sure about the default behavior either.  Maybe in a future version the auto-detection will no longer be default.

**Comment by itamarcu** [comment]
I changed it to no longer be default in v1.7.0.

**Comment by kristianserrano** [comment]
I saw! Thank you!

**Comment by shemetz** [comment]
Partially resolved by new addition of keyboard shortcuts to toggle the mode in v1.11.0.  Hopefully this will be enough to solve it for you.
