### ISSUE TITLE
[BUG] Rotation Error

### ISSUE THREAD

**Issue by Cup-of-Coffee** [shemetz/ZoomPanOptions#42]
When you rotate a token on the latest stable version of Foundry (v10, build 291), a token will not rotate and give a error.

This was narrowed down by testing on a new world with only Zoom/Pan Options and LibWrapper mod enabled.

![Screenshot 2022-12-03 193807](https://user-images.githubusercontent.com/39238717/205468348-124a9066-7cb5-43be-973b-ff514713937c.png)

**Comment by shemetz** [comment]
Fixing this in v1.8.5 (released now), thank you for the bug report!

This bug affects only Foundry v10.291 (not v10.290), for the record.
