### ISSUE TITLE
Rotation Rate Limit Is Undefined

### ISSUE THREAD

**Issue by Jacob-Lisner** [shemetz/ZoomPanOptions#50]
(Note this is version 10) - 
game.mouse.MOUSE_WHEEL_RATE_LIMIT should be game.mouse.constructor.MOUSE_WHEEL_RATE_LIMIT on line 25. The current value is undefined and causes there to be no effective rate limit.

**Comment by shemetz** [comment]
Oh, fixed in [1.12.0](https://github.com/shemetz/ZoomPanOptions/releases/tag/1.12.0), I forgot to comment that!
