### ISSUE TITLE
[BUG] Scene lags when panning and freezes screen completely

### ISSUE THREAD

**Issue by biggusbeardus** [shemetz/ZoomPanOptions#53]
When zoomed out for a wide view of a scene, the panning will freeze and you can't click on anything or zoom back in. Everything is frozen on Foundry. 

I removed the module and the behavior stopped.

Zoom/Pan Options: 1.10.0
Foundry 11.308
Pathfinder 2e 5.4.2
Forge Hosting
Chrome browser with hardware acceleration active
Nvidia GeForce RTX 3060 with 12 GB of dedicated video ram

**Comment by shemetz** [comment]
I can't reproduce this myself.

@biggusbeardus , does it happen with no other modules enabled, except ZPO?

Also, can you share a screenshot of how wide the view of the scene is, and a screenshot of your ZPO settings if you changed them?

**Comment by biggusbeardus** [comment]
Nevermind. I tried to retract my report. It's not your module. Sorry to
trouble you.
