### ISSUE TITLE
Two-finger pan triggering mousewheel zoom

### ISSUE THREAD

**Issue by this-gavagai** [shemetz/ZoomPanOptions#54]
First, thanks for this wonderful module. It's my first new install on a new system, and the QoL improvements for touchpad play are so great. My table really appreciates the work that has gone into this.

I'm encountering a problem that seems to be new. 

When using two fingers to pan, Foundry seems to sometimes also be picking up instructions to zoom. When I pan left-right, everything is fine and works as expected. When I pan the map down, however, the map also zooms in. When I pan the map up, the map also zooms out. This suggests to me that when panning up-down, foundry seems to *also* be picking up mousewheel scroll instructions, causing the map to zoom.

I believe I have Touchpad mode configured correctly for Zoom Pan Options, and I know this has worked better for me for a long while now. I'm not entirely sure what has changed, and I've not been able to suss that out by testing different modules or settings. Any suggestions will be much appreciated, as these circumstances have made touchpad interaction much more difficult.

**Comment by shemetz** [comment]
Can you give me more system information?  Is this a Mac?  is this on Firefox?  can you send a video or recording?

**Comment by this-gavagai** [comment]
Hi Shemetz, thanks for your reply. I did a bit more digging just now and it seems that the issue is that the trackpad autodetect seems not to be working correctly for me. When I turn off autodetect and select the input type manually, it works as expected. I didn't suspect that before because the trackpad *does* work, just with the unexpected scrolling behavior.

This is a recent Macbook Pro on Chrome. I'll keep digging with different browsers, etc. The autodetect was convenient, but manually setting the input type is still far better than without this module of course. I'm happy to close this issue likewise, or I can send a video if it'd still be helpful.

**Comment by shemetz** [comment]
Thanks!  I know the autodetect is pretty bad, so I think I'll leave it default off permanently (maybe with an extra warning?) unless someone can figure out how to fix it.

**Comment by this-gavagai** [comment]
Awesome. The autodetect is a nice-to-have feature but not more. I'm back to happily using my touchpad. Thanks again for your work!
