### ISSUE TITLE
[Compatibility] Module does not work in Shadowdark system

### ISSUE THREAD

**Issue by nschoenwald** [shemetz/ZoomPanOptions#57]
I figured this module would be system neutral, but unfortunately it does not seem to work in the Shadowdark system. The scene stays blank when the module is enabled. I only have Zoom / Pan options and libWrapper enabled.

<img width="1728" alt="image" src="https://github.com/shemetz/ZoomPanOptions/assets/72390280/d80e351c-f971-479e-9156-3944e3f2b382">

**Comment by shemetz** [comment]
Sweet!
