### ISSUE TITLE
Zooming out on a big scene

### ISSUE THREAD

**Issue by TrofimSelbs** [shemetz/ZoomPanOptions#64]
Hey, good day to you! Thank you for creating such a wonderful module! I have an issue. I run a call of cthulhu game and there are some big scenes that I use as maps (for example a map of old Boston). However, I can't zoom out fully out of those maps. I will include the boston map [here](https://www.loc.gov/item/2007626044/) (I use 1562x2175рх JPEG one). Could you please take a look at it?

I am running v11 315. This also happens with D&D 5e 3.1.2

**Comment by shemetz** [comment]
Have you configured the Zoom/Pan Options settings to increase the minimum and maximum zoom overrides?

![image](https://github.com/user-attachments/assets/717a834e-410b-4bbe-a866-e1091f09b1b6)

Try decreasing the Minimum further (and tell me which numbers they both are at).

**Comment by shemetz** [comment]
I admit I made the same mistake too, more than once 🗡️ 
I should probably improve those descriptions.
